//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morpher.MorpherWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://morpher.ru/", ConfigurationName="MorpherWebService.WebServiceSoap")]
    internal interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since message SubmitCorrectionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/SubmitCorrection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.MorpherWebService.SubmitCorrectionResponse SubmitCorrection(Morpher.MorpherWebService.SubmitCorrectionRequest request);
        
        // CODEGEN: Generating message contract since message GetAccountStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetAccountStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.MorpherWebService.GetAccountStatusResponse GetAccountStatus(Morpher.MorpherWebService.GetAccountStatusRequest request);
        
        // CODEGEN: Generating message contract since message GetXmlRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.MorpherWebService.GetXmlResponse GetXml(Morpher.MorpherWebService.GetXmlRequest request);
        
        // CODEGEN: Generating message contract since message GetXmlUkrRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetXmlUkr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.MorpherWebService.GetXmlUkrResponse GetXmlUkr(Morpher.MorpherWebService.GetXmlUkrRequest request);
        
        // CODEGEN: Generating message contract since message PropisRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/Propis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.MorpherWebService.PropisResponse Propis(Morpher.MorpherWebService.PropisRequest request);
        
        // CODEGEN: Generating message contract since message PropisUkrRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/PropisUkr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Morpher.MorpherWebService.PropisUkrResponse PropisUkr(Morpher.MorpherWebService.PropisUkrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/GetDailyQueryLimit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetDailyQueryLimit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://morpher.ru/ValidateClientID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidateClientID(string clientID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class Credentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class PropisUkrResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FormsUkr nField;
        
        private FormsUkr unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FormsUkr n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
                this.RaisePropertyChanged("n");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FormsUkr unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetXmlUkrResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class FormsUkr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string нField;
        
        private string рField;
        
        private string дField;
        
        private string зField;
        
        private string оField;
        
        private string мField;
        
        private string кField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Н {
            get {
                return this.нField;
            }
            set {
                this.нField = value;
                this.RaisePropertyChanged("Н");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Р {
            get {
                return this.рField;
            }
            set {
                this.рField = value;
                this.RaisePropertyChanged("Р");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Д {
            get {
                return this.дField;
            }
            set {
                this.дField = value;
                this.RaisePropertyChanged("Д");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string З {
            get {
                return this.зField;
            }
            set {
                this.зField = value;
                this.RaisePropertyChanged("З");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string О {
            get {
                return this.оField;
            }
            set {
                this.оField = value;
                this.RaisePropertyChanged("О");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string М {
            get {
                return this.мField;
            }
            set {
                this.мField = value;
                this.RaisePropertyChanged("М");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string К {
            get {
                return this.кField;
            }
            set {
                this.кField = value;
                this.RaisePropertyChanged("К");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class GetXmlUkrResult : FormsUkr {
        
        private string рідField;
        
        private Forms множинаField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string рід {
            get {
                return this.рідField;
            }
            set {
                this.рідField = value;
                this.RaisePropertyChanged("рід");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Forms множина {
            get {
                return this.множинаField;
            }
            set {
                this.множинаField = value;
                this.RaisePropertyChanged("множина");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetXmlResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class Forms : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string иField;
        
        private string рField;
        
        private string дField;
        
        private string вField;
        
        private string тField;
        
        private string пField;
        
        private string поField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string И {
            get {
                return this.иField;
            }
            set {
                this.иField = value;
                this.RaisePropertyChanged("И");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Р {
            get {
                return this.рField;
            }
            set {
                this.рField = value;
                this.RaisePropertyChanged("Р");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Д {
            get {
                return this.дField;
            }
            set {
                this.дField = value;
                this.RaisePropertyChanged("Д");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string В {
            get {
                return this.вField;
            }
            set {
                this.вField = value;
                this.RaisePropertyChanged("В");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Т {
            get {
                return this.тField;
            }
            set {
                this.тField = value;
                this.RaisePropertyChanged("Т");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string П {
            get {
                return this.пField;
            }
            set {
                this.пField = value;
                this.RaisePropertyChanged("П");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("П-о", Order=6)]
        public string По {
            get {
                return this.поField;
            }
            set {
                this.поField = value;
                this.RaisePropertyChanged("По");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class GetXmlResult : Forms {
        
        private string родField;
        
        private Forms множественноеField;
        
        private string гдеField;
        
        private string кудаField;
        
        private string откудаField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string род {
            get {
                return this.родField;
            }
            set {
                this.родField = value;
                this.RaisePropertyChanged("род");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Forms множественное {
            get {
                return this.множественноеField;
            }
            set {
                this.множественноеField = value;
                this.RaisePropertyChanged("множественное");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string где {
            get {
                return this.гдеField;
            }
            set {
                this.гдеField = value;
                this.RaisePropertyChanged("где");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string куда {
            get {
                return this.кудаField;
            }
            set {
                this.кудаField = value;
                this.RaisePropertyChanged("куда");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string откуда {
            get {
                return this.откудаField;
            }
            set {
                this.откудаField = value;
                this.RaisePropertyChanged("откуда");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://morpher.ru/")]
    public partial class PropisResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Forms nField;
        
        private Forms unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Forms n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
                this.RaisePropertyChanged("n");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Forms unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitCorrection", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    internal partial class SubmitCorrectionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.MorpherWebService.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public Morpher.MorpherWebService.GetXmlResult correction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=1)]
        public string comment;
        
        public SubmitCorrectionRequest() {
        }
        
        public SubmitCorrectionRequest(Morpher.MorpherWebService.Credentials Credentials, Morpher.MorpherWebService.GetXmlResult correction, string comment) {
            this.Credentials = Credentials;
            this.correction = correction;
            this.comment = comment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitCorrectionResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    internal partial class SubmitCorrectionResponse {
        
        public SubmitCorrectionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountStatus", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    internal partial class GetAccountStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.MorpherWebService.Credentials Credentials;
        
        public GetAccountStatusRequest() {
        }
        
        public GetAccountStatusRequest(Morpher.MorpherWebService.Credentials Credentials) {
            this.Credentials = Credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountStatusResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    internal partial class GetAccountStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string GetAccountStatusResult;
        
        public GetAccountStatusResponse() {
        }
        
        public GetAccountStatusResponse(string GetAccountStatusResult) {
            this.GetAccountStatusResult = GetAccountStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXml", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    internal partial class GetXmlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.MorpherWebService.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string s;
        
        public GetXmlRequest() {
        }
        
        public GetXmlRequest(Morpher.MorpherWebService.Credentials Credentials, string s) {
            this.Credentials = Credentials;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXmlResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    internal partial class GetXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public Morpher.MorpherWebService.GetXmlResult GetXmlResult;
        
        public GetXmlResponse() {
        }
        
        public GetXmlResponse(Morpher.MorpherWebService.GetXmlResult GetXmlResult) {
            this.GetXmlResult = GetXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXmlUkr", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    internal partial class GetXmlUkrRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.MorpherWebService.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public string s;
        
        public GetXmlUkrRequest() {
        }
        
        public GetXmlUkrRequest(Morpher.MorpherWebService.Credentials Credentials, string s) {
            this.Credentials = Credentials;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXmlUkrResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    internal partial class GetXmlUkrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public Morpher.MorpherWebService.GetXmlUkrResult GetXmlUkrResult;
        
        public GetXmlUkrResponse() {
        }
        
        public GetXmlUkrResponse(Morpher.MorpherWebService.GetXmlUkrResult GetXmlUkrResult) {
            this.GetXmlUkrResult = GetXmlUkrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Propis", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    internal partial class PropisRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.MorpherWebService.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public uint n;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=1)]
        public string unit;
        
        public PropisRequest() {
        }
        
        public PropisRequest(Morpher.MorpherWebService.Credentials Credentials, uint n, string unit) {
            this.Credentials = Credentials;
            this.n = n;
            this.unit = unit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PropisResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    internal partial class PropisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public Morpher.MorpherWebService.PropisResult PropisResult;
        
        public PropisResponse() {
        }
        
        public PropisResponse(Morpher.MorpherWebService.PropisResult PropisResult) {
            this.PropisResult = PropisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PropisUkr", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    internal partial class PropisUkrRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://morpher.ru/")]
        public Morpher.MorpherWebService.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public uint n;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=1)]
        public string unit;
        
        public PropisUkrRequest() {
        }
        
        public PropisUkrRequest(Morpher.MorpherWebService.Credentials Credentials, uint n, string unit) {
            this.Credentials = Credentials;
            this.n = n;
            this.unit = unit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PropisUkrResponse", WrapperNamespace="http://morpher.ru/", IsWrapped=true)]
    internal partial class PropisUkrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://morpher.ru/", Order=0)]
        public Morpher.MorpherWebService.PropisUkrResult PropisUkrResult;
        
        public PropisUkrResponse() {
        }
        
        public PropisUkrResponse(Morpher.MorpherWebService.PropisUkrResult PropisUkrResult) {
            this.PropisUkrResult = PropisUkrResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface WebServiceSoapChannel : Morpher.MorpherWebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Morpher.MorpherWebService.WebServiceSoap>, Morpher.MorpherWebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.MorpherWebService.SubmitCorrectionResponse Morpher.MorpherWebService.WebServiceSoap.SubmitCorrection(Morpher.MorpherWebService.SubmitCorrectionRequest request) {
            return base.Channel.SubmitCorrection(request);
        }
        
        public void SubmitCorrection(Morpher.MorpherWebService.Credentials Credentials, Morpher.MorpherWebService.GetXmlResult correction, string comment) {
            Morpher.MorpherWebService.SubmitCorrectionRequest inValue = new Morpher.MorpherWebService.SubmitCorrectionRequest();
            inValue.Credentials = Credentials;
            inValue.correction = correction;
            inValue.comment = comment;
            Morpher.MorpherWebService.SubmitCorrectionResponse retVal = ((Morpher.MorpherWebService.WebServiceSoap)(this)).SubmitCorrection(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.MorpherWebService.GetAccountStatusResponse Morpher.MorpherWebService.WebServiceSoap.GetAccountStatus(Morpher.MorpherWebService.GetAccountStatusRequest request) {
            return base.Channel.GetAccountStatus(request);
        }
        
        public string GetAccountStatus(Morpher.MorpherWebService.Credentials Credentials) {
            Morpher.MorpherWebService.GetAccountStatusRequest inValue = new Morpher.MorpherWebService.GetAccountStatusRequest();
            inValue.Credentials = Credentials;
            Morpher.MorpherWebService.GetAccountStatusResponse retVal = ((Morpher.MorpherWebService.WebServiceSoap)(this)).GetAccountStatus(inValue);
            return retVal.GetAccountStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.MorpherWebService.GetXmlResponse Morpher.MorpherWebService.WebServiceSoap.GetXml(Morpher.MorpherWebService.GetXmlRequest request) {
            return base.Channel.GetXml(request);
        }
        
        public Morpher.MorpherWebService.GetXmlResult GetXml(Morpher.MorpherWebService.Credentials Credentials, string s) {
            Morpher.MorpherWebService.GetXmlRequest inValue = new Morpher.MorpherWebService.GetXmlRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            Morpher.MorpherWebService.GetXmlResponse retVal = ((Morpher.MorpherWebService.WebServiceSoap)(this)).GetXml(inValue);
            return retVal.GetXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.MorpherWebService.GetXmlUkrResponse Morpher.MorpherWebService.WebServiceSoap.GetXmlUkr(Morpher.MorpherWebService.GetXmlUkrRequest request) {
            return base.Channel.GetXmlUkr(request);
        }
        
        public Morpher.MorpherWebService.GetXmlUkrResult GetXmlUkr(Morpher.MorpherWebService.Credentials Credentials, string s) {
            Morpher.MorpherWebService.GetXmlUkrRequest inValue = new Morpher.MorpherWebService.GetXmlUkrRequest();
            inValue.Credentials = Credentials;
            inValue.s = s;
            Morpher.MorpherWebService.GetXmlUkrResponse retVal = ((Morpher.MorpherWebService.WebServiceSoap)(this)).GetXmlUkr(inValue);
            return retVal.GetXmlUkrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.MorpherWebService.PropisResponse Morpher.MorpherWebService.WebServiceSoap.Propis(Morpher.MorpherWebService.PropisRequest request) {
            return base.Channel.Propis(request);
        }
        
        public Morpher.MorpherWebService.PropisResult Propis(Morpher.MorpherWebService.Credentials Credentials, uint n, string unit) {
            Morpher.MorpherWebService.PropisRequest inValue = new Morpher.MorpherWebService.PropisRequest();
            inValue.Credentials = Credentials;
            inValue.n = n;
            inValue.unit = unit;
            Morpher.MorpherWebService.PropisResponse retVal = ((Morpher.MorpherWebService.WebServiceSoap)(this)).Propis(inValue);
            return retVal.PropisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Morpher.MorpherWebService.PropisUkrResponse Morpher.MorpherWebService.WebServiceSoap.PropisUkr(Morpher.MorpherWebService.PropisUkrRequest request) {
            return base.Channel.PropisUkr(request);
        }
        
        public Morpher.MorpherWebService.PropisUkrResult PropisUkr(Morpher.MorpherWebService.Credentials Credentials, uint n, string unit) {
            Morpher.MorpherWebService.PropisUkrRequest inValue = new Morpher.MorpherWebService.PropisUkrRequest();
            inValue.Credentials = Credentials;
            inValue.n = n;
            inValue.unit = unit;
            Morpher.MorpherWebService.PropisUkrResponse retVal = ((Morpher.MorpherWebService.WebServiceSoap)(this)).PropisUkr(inValue);
            return retVal.PropisUkrResult;
        }
        
        public int GetDailyQueryLimit() {
            return base.Channel.GetDailyQueryLimit();
        }
        
        public bool ValidateClientID(string clientID) {
            return base.Channel.ValidateClientID(clientID);
        }
    }
}
